include:
  - board: xiao_ble
    shield: totem_left
    snippet: zmk-usb-logging
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
    snippet: zmk-usb-logging
  # - board: xiao_ble
  #   shield: totem_dongle
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: xiao_ble
  #   shield: settings_reset
